apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: june19-db-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/june19-db-1:cb173b92ce2b3e251ef00da02833aacff9605deb@sha256:7fc52a3b47c3ddeb95b156181699df18febc9728e858f7215786e5d5b7e3ca8d # use pre-built to bootstrap
          name: app-inference
